services:
  inventory_db:
    image: postgres:15-alpine
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies_db
    ports:
      - "5432:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
  billing_db:
    image: postgres:15-alpine
    container_name: billing_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billing_db
    ports:
      - "5433:5432"
    volumes:
      - billing_data:/var/lib/postgresql/data
volumes:
  inventory_data:
  billing_data:
